name: Release NPM (latest)

on:
  push:
    branches: [dev]

jobs:
  version-update:
    name: Update version and push to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Configure Git
      - run: |
          git config --global user.email blinq.io@blinq.io
          git config --global user.name blinq.io
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm version patch
      - run: git push --follow-tags origin dev

  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    needs: version-update
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install-test
      - uses: cucumber/action-publish-npm@v1.1.0
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          npm-tag: 'next'
